package edu.daoProject;

import edu.daoProject.dao.UniversalDao;
import edu.daoProject.model.Employee;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.ApplicationContext;
import org.springframework.context.annotation.AnnotationConfigApplicationContext;
import org.springframework.stereotype.Component;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.List;


public class Main {
    public static void main(String[] args) {
        System.out.println("dao");
//        try {
//            Connection connection = DriverManager.getConnection("jdbc:h2:file:./h2db");
//            Statement statement = connection.createStatement();
//            statement.execute("CREATE TABLE Employee (id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name VARCHAR(100), department INT NOT NULL)");
//            statement.execute("INSERT INTO Employee (name, department) VALUES ('dan', 1) ");
//        } catch (Exception e) {
//            throw new RuntimeException(e);
//        }


        ApplicationContext ctx = new AnnotationConfigApplicationContext("edu.daoProject");
        UniversalDao<Employee, Integer> dbEmp = ctx.getBean("EmployeeDao", UniversalDao.class);
        List<Employee> emps = dbEmp.findAll();
        System.out.println(emps);
        System.out.println(dbEmp.findByID(2));

        Employee employee1 = new Employee("very-new5-4", 1);
        Employee employee2 = new Employee("very-new5-2", 1);
        System.out.println(employee1 + " " + employee2);
        boolean ins = dbEmp.insertOne(employee1);
//        int ins = dbEmp.insertMany(employee1, employee2);
        System.out.println(ins);
        System.out.println(employee1 + " " + employee2);
//        System.out.println(dbEmp.findByID(employee1.getId()));
        System.out.println(dbEmp.findAll());
        employee1.setName("new name");
        System.out.println(employee1);
        boolean ins2 = dbEmp.updateOne(employee1);
        System.out.println(ins2);
        System.out.println(dbEmp.findAll());
        ins2 = dbEmp.updateOne(new Employee("test-1", 2));
        System.out.println(ins2);
        System.out.println(dbEmp.findAll());


//        System.out.println(Employee.class.getDeclaredFields()[1].getName());

    }
}
